// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum CNmTransitionNodeTransitionOptions_t : byte
{
	None = 0x0,
	ClampDuration = 0x1,
	Synchronized = 0x2,
	MatchSourceTime = 0x4,
	MatchSyncEventIndex = 0x8,
	MatchSyncEventID = 0x10,
	MatchSyncEventPercentage = 0x20,
	PreferClosestSyncEventID = 0x40,
}
