// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum NmPoseBlendMode_t : byte
{
	Overlay = 0x0,
	Additive = 0x1,
	GlobalSpace = 0x2,
}
